export const services = [
  {
    slug: "visa-americana",
    icon: "visa",
    title: "Asesoria para visa americana",
    text: "Orientacion clara sobre requisitos, etapas y preparacion general del proceso.",
    time: "Revision inicial: 24 a 48 horas. Preparacion completa: 3 a 7 dias habiles, segun la informacion entregada por el cliente.",
    requirements: [
      "Pasaporte vigente.",
      "Informacion personal, laboral, familiar y economica actualizada.",
      "Motivo del viaje, fechas tentativas y lugar de estadia.",
      "Historial de viajes anteriores, si aplica.",
      "Documentos de respaldo segun el perfil del solicitante.",
    ],
    process: [
      "Analisis inicial del caso y objetivo de viaje.",
      "Revision de informacion y documentos de soporte.",
      "Orientacion para completar datos del formulario correspondiente.",
      "Preparacion general para la entrevista consular.",
      "Seguimiento hasta que el cliente tenga claridad sobre los siguientes pasos.",
    ],
  },
  {
    slug: "organizacion-documentos",
    icon: "document",
    title: "Organizacion de documentos",
    text: "Clasificamos la informacion de respaldo para que tengas un expediente mas ordenado.",
    time: "Organizacion base: 24 a 72 horas. Casos con mayor volumen documental: 3 a 5 dias habiles.",
    requirements: [
      "Documento de identidad y pasaporte, si aplica.",
      "Comprobantes laborales, comerciales o academicos disponibles.",
      "Soportes financieros recientes.",
      "Documentos familiares o de arraigo, cuando sean relevantes.",
      "Cualquier documento relacionado con el motivo del tramite.",
    ],
    process: [
      "Recepcion de documentos disponibles.",
      "Clasificacion por tipo de soporte y relevancia.",
      "Identificacion de documentos faltantes o confusos.",
      "Entrega de una guia organizada para completar el expediente.",
    ],
  },
  {
    slug: "preparacion-entrevista",
    icon: "interview",
    title: "Preparacion para entrevista",
    text: "Te guiamos con recomendaciones practicas para responder con seguridad y coherencia.",
    time: "Sesion de preparacion: 60 a 90 minutos. Preparacion con simulacion: 1 a 2 dias habiles.",
    requirements: [
      "Resumen claro del motivo de viaje.",
      "Informacion sobre empleo, estudios, negocio o actividad actual.",
      "Datos sobre familiares, estadia y fechas tentativas.",
      "Documentos principales que respalden el caso.",
    ],
    process: [
      "Revision de puntos fuertes y dudas del caso.",
      "Practica de preguntas frecuentes.",
      "Recomendaciones para responder con claridad y coherencia.",
      "Retroalimentacion sobre seguridad, orden y consistencia.",
    ],
  },
  {
    slug: "planificacion-viaje",
    icon: "plane",
    title: "Planificacion de viaje",
    text: "Apoyo para estructurar fechas, motivos de viaje y detalles importantes.",
    time: "Plan basico: 24 a 48 horas. Itinerario mas detallado: 2 a 4 dias habiles.",
    requirements: [
      "Objetivo principal del viaje.",
      "Ciudad o ciudades de destino.",
      "Fechas tentativas de salida y regreso.",
      "Datos de hospedaje o contacto en destino, si existen.",
      "Presupuesto estimado y acompanantes, si aplica.",
    ],
    process: [
      "Definicion del motivo y ruta de viaje.",
      "Revision de fechas y coherencia del itinerario.",
      "Organizacion de informacion de hospedaje y actividades.",
      "Alineacion del plan con la informacion del tramite.",
    ],
  },
  {
    slug: "seguimiento-proceso",
    icon: "steps",
    title: "Seguimiento del proceso",
    text: "Acompanamiento durante las etapas principales para resolver dudas oportunamente.",
    time: "Respuesta a consultas: 24 a 48 horas habiles. Seguimiento activo durante las etapas acordadas del servicio.",
    requirements: [
      "Estado actual del tramite.",
      "Comprobantes, confirmaciones o comunicaciones recibidas.",
      "Fechas importantes del proceso.",
      "Dudas puntuales para revisar.",
    ],
    process: [
      "Revision del avance reportado por el cliente.",
      "Aclaracion de dudas segun la etapa del proceso.",
      "Recordatorio de pasos pendientes.",
      "Acompanamiento por los canales acordados.",
    ],
  },
  {
    slug: "formularios-requisitos",
    icon: "compass",
    title: "Formularios y requisitos",
    text: "Orientacion para comprender informacion solicitada y evitar errores frecuentes.",
    time: "Revision de datos: 24 a 72 horas. Formularios extensos o casos familiares: 3 a 6 dias habiles.",
    requirements: [
      "Datos personales completos y actualizados.",
      "Historial laboral, academico y de viajes.",
      "Informacion familiar y de contacto.",
      "Datos del viaje o tramite a realizar.",
      "Documentos de soporte para validar informacion clave.",
    ],
    process: [
      "Revision de la informacion solicitada.",
      "Identificacion de datos incompletos o inconsistentes.",
      "Orientacion para completar campos relevantes.",
      "Revision final antes de avanzar a la siguiente etapa.",
    ],
  },
];

export function getServiceBySlug(slug) {
  return services.find((service) => service.slug === slug);
}
